import fs from 'fs'

const modal = [
  "import { useEffect, useState } from 'react'",
  "import { Button, Form, Modal, Select, Switch, Upload, message } from 'antd'",
  "import { InboxOutlined } from '@ant-design/icons'",
  "import { getCategoriesFlat, importBookmarks } from '../api'",
  "",
  "type Props = {",
  "  open: boolean",
  "  onClose: () => void",
  "  onSuccess?: () => void",
  "}",
  "",
  "function SwitchRow({",
  "  value,",
  "  onChange,",
  "}: {",
  "  value?: boolean",
  "  onChange?: (v: boolean) => void",
  "}) {",
  "  return (",
  "    <div className=\"admin-switch-row\">",
  "      <div>",
  "        <strong>\u5BFC\u5165\u4E3A\u79C1\u6709</strong>",
  "        <span>\u5F00\u542F\u540E\uFF0C\u672A\u767B\u5F55\u7528\u6237\u5728\u524D\u53F0\u4E0D\u53EF\u89C1</span>",
  "      </div>",
  "      <Switch checked={!!value} onChange={onChange} />",
  "    </div>",
  "  )",
  "}",
  "",
  "export default function BookmarkImportModal({ open, onClose, onSuccess }: Props) {",
  "  const [categories, setCategories] = useState<{ id: number; name: string }[]>([])",
  "  const [html, setHtml] = useState('')",
  "  const [fileName, setFileName] = useState('')",
  "  const [loading, setLoading] = useState(false)",
  "  const [form] = Form.useForm()",
  "",
  "  useEffect(() => {",
  "    if (!open) return",
  "    getCategoriesFlat().then((res: any) => setCategories(res.data || []))",
  "    form.resetFields()",
  "    form.setFieldsValue({ private: false })",
  "    setHtml('')",
  "    setFileName('')",
  "  }, [open, form])",
  "",
  "  const onImport = async () => {",
  "    const values = await form.validateFields()",
  "    if (!html) {",
  "      message.warning('\u8BF7\u5148\u4E0A\u4F20\u4E66\u7B7E HTML \u6587\u4EF6')",
  "      return",
  "    }",
  "    setLoading(true)",
  "    try {",
  "      const res: any = await importBookmarks({",
  "        html,",
  "        category_id: values.category_id,",
  "        private: values.private || false,",
  "      })",
  "      message.success(`\u89E3\u6790 ${res.data.parsed} \u6761\uFF0C\u6210\u529F\u5BFC\u5165 ${res.data.imported} \u6761`)",
  "      onClose()",
  "      onSuccess?.()",
  "    } catch (e) {",
  "      message.error((e as Error).message)",
  "    } finally {",
  "      setLoading(false)",
  "    }",
  "  }",
  "",
  "  return (",
  "    <Modal",
  "      className=\"admin-modal bookmark-import-modal\"",
  "      title={",
  "        <div>",
  "          <div>\u4E66\u7B7E\u5BFC\u5165</div>",
  "          <div className=\"admin-modal-subtitle\">\u5BFC\u5165 Chrome / Edge \u5BFC\u51FA\u7684\u4E66\u7B7E HTML</div>",
  "        </div>",
  "      }",
  "      open={open}",
  "      onCancel={onClose}",
  "      onOk={onImport}",
  "      confirmLoading={loading}",
  "      okText=\"\u5F00\u59CB\u5BFC\u5165\"",
  "      cancelText=\"\u53D6\u6D88\"",
  "      width={560}",
  "      centered",
  "      destroyOnHidden",
  "    >",
  "      <ol className=\"bookmark-steps\">",
  "        <li>",
  "          <span className=\"bookmark-step-num\">1</span>",
  "          <div className=\"bookmark-step-body\">",
  "            <strong>\u5BFC\u51FA\u4E66\u7B7E</strong>",
  "            <p>\u6D4F\u89C8\u5668\u6253\u5F00\u4E66\u7B7E\u7BA1\u7406\u5668 \u2192 \u5BFC\u51FA\u4E66\u7B7E\uFF0C\u5F97\u5230 .html \u6587\u4EF6</p>",
  "          </div>",
  "        </li>",
  "        <li>",
  "          <span className=\"bookmark-step-num\">2</span>",
  "          <div className=\"bookmark-step-body\">",
  "            <strong>\u9009\u62E9\u76EE\u6807\u5206\u7C7B</strong>",
  "            <p>\u5BFC\u5165\u7684\u94FE\u63A5\u4F1A\u5165\u5230\u4F60\u6307\u5B9A\u7684\u5206\u7C7B\u4E0B</p>",
  "          </div>",
  "        </li>",
  "        <li>",
  "          <span className=\"bookmark-step-num\">3</span>",
  "          <div className=\"bookmark-step-body\">",
  "            <strong>\u4E0A\u4F20\u5E76\u5BFC\u5165</strong>",
  "            <p>\u4E0A\u4F20 HTML \u540E\u70B9\u51FB\u300C\u5F00\u59CB\u5BFC\u5165\u300D</p>",
  "          </div>",
  "        </li>",
  "      </ol>",
  "",
  "      <Form form={form} layout=\"vertical\" className=\"admin-form\" initialValues={{ private: false }}>",
  "        <div className=\"admin-form-block\">",
  "          <div className=\"admin-form-block-title\">\u5BFC\u5165\u8BBE\u7F6E</div>",
  "          <Form.Item",
  "            name=\"category_id\"",
  "            label=\"\u5BFC\u5165\u5230\u5206\u7C7B\"",
  "            rules={[{ required: true, message: '\u8BF7\u9009\u62E9\u5206\u7C7B' }]}",
  "          >",
  "            <Select",
  "              allowClear={false}",
  "              placeholder=\"\u8BF7\u5148\u5728\u5206\u7C7B\u5217\u8868\u521B\u5EFA\u5206\u7C7B\"",
  "              options={categories.map((c) => ({ label: c.name, value: c.id }))}",
  "            />",
  "          </Form.Item>",
  "          <Form.Item name=\"private\" style={{ marginBottom: 0 }}>",
  "            <SwitchRow />",
  "          </Form.Item>",
  "        </div>",
  "",
  "        <div className=\"admin-form-block\">",
  "          <div className=\"admin-form-block-title\">\u4E66\u7B7E\u6587\u4EF6</div>",
  "          <Form.Item style={{ marginBottom: 0 }}>",
  "            <Upload.Dragger",
  "              className=\"bookmark-uploader\"",
  "              accept=\".html,.htm\"",
  "              maxCount={1}",
  "              showUploadList={false}",
  "              beforeUpload={(file) => {",
  "                const reader = new FileReader()",
  "                reader.onload = () => {",
  "                  setHtml(String(reader.result || ''))",
  "                  setFileName(file.name)",
  "                  message.success(`\u5DF2\u9009\u62E9 ${file.name}`)",
  "                }",
  "                reader.readAsText(file)",
  "                return false",
  "              }}",
  "            >",
  "              <p className=\"ant-upload-drag-icon\">",
  "                <InboxOutlined />",
  "              </p>",
  "              <p className=\"ant-upload-text\">",
  "                {fileName ? `\u5DF2\u9009\u62E9\uFF1A${fileName}` : '\u70B9\u51FB\u6216\u62D6\u62FD\u4E0A\u4F20 bookmarks.html'}",
  "              </p>",
  "              <p className=\"ant-upload-hint\">\u4EC5\u652F\u6301 Chrome / Edge \u5BFC\u51FA\u7684 .html / .htm \u6587\u4EF6</p>",
  "            </Upload.Dragger>",
  "          </Form.Item>",
  "          {fileName ? (",
  "            <div className=\"bookmark-file-bar\">",
  "              <span>{fileName}</span>",
  "              <Button",
  "                type=\"link\"",
  "                danger",
  "                onClick={() => {",
  "                  setHtml('')",
  "                  setFileName('')",
  "                }}",
  "              >",
  "                \u79FB\u9664",
  "              </Button>",
  "            </div>",
  "          ) : null}",
  "        </div>",
  "      </Form>",
  "    </Modal>",
  "  )",
  "}",
  "",
].join('\n')

fs.writeFileSync('src/components/BookmarkImportModal.tsx', modal, 'utf8')
console.log('modal', fs.readFileSync('src/components/BookmarkImportModal.tsx', 'utf8').includes('\u4E66\u7B7E\u5BFC\u5165'))
